language: node_js
node_js:
  - '0.10'
  - '0.11'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-gulp-plugin' ]; then cd .. && eval "mv $currentfolder generator-gulp-plugin" && cd generator-gulp-plugin; fi
